### ISSUE TITLE
Lagerbestand Update 

### ISSUE THREAD

**Issue by doitauto** [FATCHIP-GmbH/plugin-shopware5-shopware2afterbuy#19]
Hallo,

es wird nur Shopbestand vom Afterbuy abgeglichen es sollte auch die Möglichkeit geben die Auktionsbestand mit SW abzugleichen, währe sehr nett wenn man es bald möglichst realisieren würde.

**Comment by FATCHIP-GmbH** [comment]
Leider wird es einen Bestandsabgleich von SW --> AB in naher Zukunft nicht geben. Sobald Afterbuy diesen Feature Request frei gibt, können wir diesen implementieren.
