### ISSUE TITLE
Bestellübertragung Problem

### ISSUE THREAD

**Issue by doitauto** [FATCHIP-GmbH/plugin-shopware5-shopware2afterbuy#34]
Hallo,

seit Heute werden meine Bestellungen nicht mehr übertragen und ich bekomme bei dem cronjob folgende Fehlermeldung:
Meine SW Version: 5.6.10
```
Task "cd /var/www/vhosts/doitauto.de/httpdocs &amp;&amp; /opt/plesk/php/7.4/bin/php bin/console Afterbuy:Update:Orders" completed with error in 1 seconds, output:

Update order status: 1



In EntityNotFoundException.php line 47:

Entity of type 'Shopware\Models\Payment\Payment' for IDs id(131) was not fo
und


Afterbuy:Update:Orders
```

**Comment by doitauto** [comment]
Hallo,

wann meldet ihr euch zweck meinem Problem???

**Comment by FATCHIP-GmbH** [comment]
Sehr geehrter Herr,

das Problem ist bei uns so nicht nachvollziehbar und da das Plugin anscheinend vorher funktioniert hat, gehen wir davon aus, dass hier kein Problem des Plugins vorliegt.
Sollte das Problem weiter bestehen, benötigen wir eine Supportvereinbarung, welches Sie unter https://www.fatchip.de/out/media/FC_Supportauftrag_Allgemein_Formular.pdf herunterladen können. Wenn es sich doch herausstellen sollte, dass es sich um ein Bug im Plugin handelt, entstehen Ihnen keine Kosten.
Mit freundlichen Grüßen
Marcel Ritter
Fatchip Support
