### ISSUE TITLE
[SW5.7.2] Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException

### ISSUE THREAD

**Issue by stiivo** [FATCHIP-GmbH/plugin-shopware5-shopware2afterbuy#35]
Nach dem Update auf Shopware 5.7.2 scheint das Plugin nicht mehr zu funktionieren:

    Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "viaeb_shopware_afterbuy.services.helper.shopware_order_helper" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. in /shopware/vendor/symfony/dependency-injection/Container.php:275 
    Stack trace: 
    #0 /shopware/vendor/symfony/dependency-injection/Container.php(231): Symfony\Component\DependencyInjection\Container->make() 
    #1 /shopware/engine/Shopware/Components/DependencyInjection/Container.php(210): Symfony\Component\DependencyInjection\Container->get() 
    #2 /shopware/engine/Shopware/Components/DependencyInjection/Container.php(134): Shopware\Components\DependencyInjection\Container->doLoad() 
    #3 /shopware/var/cache/production_202106241450/proxies/ShopwareProduction97140e63fe8eab0eba00ab7856fca36864424c1fProjectContainer.php(9562):
    	Shopware\Components\DependencyInjection\Conta in /shopware/vendor/symfony/dependency-injection/Container.php on line 275

grüße

**Comment by FATCHIP-GmbH** [comment]
Das Problem besteht seit der Version 1.0.4 nicht mehr
